---
title: "XAI3"
author: "adrià"
date: "2024-05-21"
output: html_document
---

```{r warning=TRUE}
library("ggplot2")
library("partykit")
#install.packages("randomForest")
#install.packages("pdp")
library("pdp")
library("randomForest")
```


```{r}
# Leer el archivo CSV
data <- read.csv("day.csv")

# Transformar la variable 'season' usando one-hot encoding
data$season <- as.factor(data$season)
season_dummies <- model.matrix(~ season - 1, data=data)
colnames(season_dummies) <- c("spring", "summer", "fall", "winter")

# Crear variables 'MISTY' y 'RAIN'
data$MISTY <- as.numeric(data$weathersit == 2)
data$RAIN <- as.numeric(data$weathersit %in% c(3, 4))

# Denormalizar 'temp', 'hum' y 'windspeed'
data$temp <- data$temp * (39 - (-8)) + (-8)
data$hum <- data$hum * 100
data$windspeed <- data$windspeed * 67

# Crear una característica que cuenta los días desde el 1 de enero de 2011
data$dteday <- as.Date(data$dteday)
start_date <- as.Date("2011-01-01")
data$days_since_2011 <- as.numeric(data$dteday - start_date)


model_data <- cbind(data[, c("workingday", "holiday", "temp", "hum", "windspeed", "MISTY", "RAIN", "cnt", "days_since_2011")], season_dummies)

# Crear y entrenar el modelo de Random Forest
rf_model <- randomForest(cnt ~ ., data = model_data, ntree = 100, importance = TRUE)

```




```{r}
# Seleccionar las características para las cuales queremos graficar el PDP
features_to_plot <- c("temp", "hum", "windspeed", "days_since_2011")

# Graficar Partial Dependence Plots
for (feature in features_to_plot) {
  pdp_plot <- partial(rf_model, pred.var = feature, grid.resolution = 50)
  plot <- autoplot(pdp_plot) +
          ggtitle(paste("Partial Dependence Plot for", feature)) +
          theme_minimal()
  print(plot)
}

```


2.- Bidimensional Partial Dependency Plot.


```{r}
library("gridExtra")
set.seed(123) 
sampled_data <- model_data[sample(nrow(model_data), 500), ]

model <- randomForest(cnt ~ temp + hum, data = sampled_data)

# Create a grid of values for temperature and humidity
temp_seq <- seq(from = min(sampled_data$temp), to = max(sampled_data$temp), length.out = 50)
hum_seq <- seq(from = min(sampled_data$hum), to = max(sampled_data$hum), length.out = 50)
grid <- expand.grid(temp = temp_seq, hum = hum_seq)

grid$predicted_cnt = predict(model, newdata = grid)
# Crear el gráfico del mapa de calor
p1 <- ggplot() +
  geom_tile(data = grid, aes(x = temp, y = hum, fill = predicted_cnt)) +  # Crear el mapa de calor 2D
  scale_fill_gradientn(colors = c("#A62957", "#D966A5", "#2180A6", "#3BC9D9")) +  # Gradiente de color personalizado
  labs(title = "Mapa de Calor de Predicciones",
       subtitle = "Efecto de la Temperatura y la Humedad en el Alquiler de Bicicletas",
       x = "Temperatura (°C)", y = "Humedad (%)",
       fill = "Número Predicho de Bicicletas Alquiladas") +
  theme_minimal()
p1
# Crear el gráfico de líneas de densidad
p2 <- ggplot() +
  geom_density_2d(data = sampled_data, aes(x = temp, y = hum), linewidth = 0.3, color = "blue") +  # Crear líneas de densidad
  labs(title = "Líneas de Densidad",
       subtitle = "Distribución de Temperatura y Humedad en los Datos Originales",
       x = "Temperatura (°C)", y = "Humedad (%)") +
  theme_minimal()
p2
# Gráfico conjunto
p3 = ggplot() +
  geom_tile(data = grid, aes(x = temp, y = hum, fill = predicted_cnt)) +  # Create the 2D plot
  geom_density_2d(data = data, aes(x = temp, y = hum), linewidth = 0.3, color = "white") +  # Overlay density lines
  scale_fill_gradientn(colors = c("#A62957", "#D966A5", "#2180A6", "#3BC9D9")) +  # Custom color gradient
  labs(title = "2D Partial Dependency Plot with Density Overlay",
       x = "Temperatura (°C)", y = "Humedad (%)",
       fill = "Predicted Number of Bikes Rented") +
  theme_minimal()
p3
#grid.arrange(p1, p2, p3, nrow = 3)

```


3. PDP to explain the price of a house.

```{r}
# Load necessary libraries
library(randomForest)
library(ggplot2)
library(dplyr)

# Load the data
datos_casa <- read.csv("kc_house_data.csv")
model_data <- cbind(datos_casa[, c("bedrooms", "bathrooms", "sqft_living", "sqft_lot", "floors", "yr_built","price")])

# Set seed for reproducibility
set.seed(123) 
sampled_data <- model_data[sample(nrow(datos_casa), 5000), ]

```

Modelo Random Forest con 5000 muestras de las 21000 observaciones.

```{r}
model <- randomForest(price ~ bedrooms + bathrooms + sqft_living + sqft_lot + floors + yr_built,
                      data = sampled_data)
```


```{r}
# Seleccionar las características para las cuales queremos graficar el PDP
features_to_plot <- c("bedrooms", "bathrooms", "sqft_living", "sqft_lot", "floors", "yr_built")

# Graficar Partial Dependence Plots
for (feature in features_to_plot) {
  pdp_plot <- partial(model, pred.var = feature, grid.resolution = 50)
  plot <- autoplot(pdp_plot) +
          ggtitle(paste("Partial Dependence Plot for", feature)) +
          theme_minimal()
  print(plot)
}
```



































